let $ = require('jquery');
$('.nav-toggle-button').on('click',function(){
    if($(this).hasClass('false')){
        $('.navbar-collapse').slideUp();
        $(this).removeClass('false');        
    }else{
        $('.navbar-collapse').slideDown();
        $(this).addClass('false');
    }  
})
$('.index').on('click',function(){
    $.ajax({
        url:'/ajax.json',
        method:'POST',
        dataType:'json'
    }).done(function(res){
        console.log(res);
    })
})